### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tatdig** [KIZI/IRAPI#1]
2017-10-03 12:46:00,844 ERROR media.MediaExtractorParser -  error in MediaParseFilter for url: http://xxxxxxxx.xxx$
java.lang.NullPointerException
        at org.apache.nutch.util.Bytes.toBytes(Bytes.java:477)
        at org.apache.nutch.parse.media.interfaces.LinkedTVEnrciher.enrich(LinkedTVEnrciher.java:65)
        at org.apache.nutch.parse.media.MediaExtractorParser.filter(MediaExtractorParser.java:107)
        at org.apache.nutch.parse.ParseFilters.filter(ParseFilters.java:106)
        at org.apache.nutch.parse.html.HtmlParser.getParse(HtmlParser.java:258)
        at org.apache.nutch.parse.ParseCallable.call(ParseCallable.java:36)
        at org.apache.nutch.parse.ParseCallable.call(ParseCallable.java:23)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by tatdig** [comment]
2017-10-03 12:46:59,164 ERROR media.MediaIndexingFilter - Error while indexing for url: http://www.xxxxxx.xxxx/ : n$
java.lang.NullPointerException
        at org.apache.nutch.parse.media.interfaces.MediaMetadataStrategy.deserialize(MediaMetadataStrategy.java:77)
        at org.apache.nutch.parse.media.interfaces.MediaMetadataStrategy.getMedia(MediaMetadataStrategy.java:55)
        at org.apache.nutch.indexer.media.MediaIndexingFilter.filter(MediaIndexingFilter.java:64)
        at org.apache.nutch.indexer.IndexingFilters.filter(IndexingFilters.java:108)
        at org.apache.nutch.indexer.IndexUtil.index(IndexUtil.java:83)
        at org.apache.nutch.indexer.IndexingJob$IndexerMapper.map(IndexingJob.java:114)
        at org.apache.nutch.indexer.IndexingJob$IndexerMapper.map(IndexingJob.java:71)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:340)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by tatdig** [comment]
2017-10-03 12:46:59,278 INFO  solr.SolrIndexWriter - Adding 1 documents
2017-10-03 12:46:59,547 WARN  mapred.LocalJobRunner - job_local145621217_0001
java.lang.Exception: java.lang.NullPointerException
        at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522)
Caused by: java.lang.NullPointerException
        at org.apache.nutch.indexwriter.media.MediaSOLRIndexWriter.write(MediaSOLRIndexWriter.java:65)
        at org.apache.nutch.indexer.IndexWriters.write(IndexWriters.java:86)
        at org.apache.nutch.indexer.IndexerOutputFormat$1.write(IndexerOutputFormat.java:48)
        at org.apache.nutch.indexer.IndexerOutputFormat$1.write(IndexerOutputFormat.java:43)
        at org.apache.hadoop.mapred.MapTask$NewDirectOutputCollector.write(MapTask.java:635)
        at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
        at org.apache.nutch.indexer.IndexingJob$IndexerMapper.map(IndexingJob.java:122)
        at org.apache.nutch.indexer.IndexingJob$IndexerMapper.map(IndexingJob.java:71)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:340)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2017-10-03 12:47:00,045 ERROR indexer.IndexingJob - SolrIndexerJob: java.lang.RuntimeException: job failed: name=a$
        at org.apache.nutch.util.NutchJob.waitForCompletion(NutchJob.java:120)
        at org.apache.nutch.indexer.IndexingJob.run(IndexingJob.java:156)
        at org.apache.nutch.indexer.IndexingJob.index(IndexingJob.java:178)
        at org.apache.nutch.indexer.IndexingJob.run(IndexingJob.java:204)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.nutch.indexer.IndexingJob.main(IndexingJob.java:213)
